### ISSUE TITLE
Table in pkgdown

### ISSUE THREAD

**Issue by NickCH-K** [NickCH-K/pmdplyr#16]
The documentation for `panel_convert()` uses a table. This looks very, very bad on the `pkgdown` page, and I'm not sure why.

**Comment by philip-khor** [comment]
I don't know LaTeX but it looks like our best shot is to somehow get ROxygen2 to work with a LaTeX macro, which doesn't seem to work with .Rd. Maybe consider moving the table to a package vignette? 

See also https://stackoverflow.com/questions/9373253/how-to-cross-reference-an-equation-in-an-r-help-file-roxygen2 which also recommends vignettes.
