### ISSUE TITLE
Add philip-khor to the dev list

### ISSUE THREAD

**Issue by NickCH-K** [NickCH-K/pmdplyr#17]
I mean, you've earned it right @philip-khor? I don't know the etiquette here.

**Comment by philip-khor** [comment]
Thanks Nick! 

Hmm I'm not sure about how it's done myself. There's two ways I could be listed: 
- listed as [author or contributor](https://r-pkgs.org/description.html) in DESCRIPTION. I'm happy to put in a PR for that. 
- listed as [collaborator for this GitHub repository](https://help.github.com/en/articles/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account), although the implications of that are quite a bit more. From what I observed, usually repo access controls are done at the level of GitHub organisations.

I think adding my details to DESCRIPTION should be alright for now.

**Comment by NickCH-K** [comment]
Sounds good! Go ahead and put in a PR for the DESCRIPTION.
