### ISSUE TITLE
Write vignettes and improve README

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#24]
I think it would be nice to have a few examples of panel data analysis in pmdplyr, perhaps as articles on pkgdown, but also (and more importantly) as part of the README, as recommended in section 2.18 [here](https://r-pkgs.org/whole-game.html#): 

> How to populate this skeleton? Copy stuff liberally from DESCRIPTION and any formal and informal tests or examples you have.

**Comment by NickCH-K** [comment]
Yeah, it's probably about that time.

**Comment by NickCH-K** [comment]
README is written in 66a3349bba3a707b9a59a1edeaa0a51394f09eff

**Comment by NickCH-K** [comment]
Vignette is written in 0771077f97cdbfb273eb49408759c884103e9c42
