### ISSUE TITLE
"Removing pibble status" warning - worth it?

### ISSUE THREAD

**Issue by NickCH-K** [NickCH-K/pmdplyr#28]
All of the `tbl_pb` methods that have the potential to remove the `.i` and `.t` variables runs through `dropchecker` to see if `pibble` status is still valid and, if so, removes it.

However, this can lead to problems if a `pibble` is sent through a function which, internally, makes some changes to it. Generally the `pibble` is returned intact, but there might be some places along the way where it gets removed, prompting the warning. This can be annoying and confusing - `panel_locf` for example doesn't even return a data frame, but it still reports the warning.

Options:

1. Remove the warning - could be an issue when someone does in fact make a change and doesn't realize they've lost `pibble` status
2. Go through and `suppressWarnings()` on all the `dplyr` verbs used internally that might drop `pibble` status
3. After getting `inp` in each function, turn any `pibble` to a `data.frame` anyway so that there's no `pibble` status to lose, internally. Then re-declare it at the end

Not sure the best way to go here.

**Comment by philip-khor** [comment]
Not entirely sure myself. Some thoughts: 
- for point 3 I think the fallback should be `tibble` instead of `data.frame`
- My impression is that the tidyverse values type consistency (e.g. the design of the `purrr` functions), and I think for most functions we should return an error whenever a pibble cannot be returned. Perhaps the user should always expect a pibble returned whenever a pmdplyr function is used. I think we should force the user to drop the pibble attributes and coerce the object into a tibble with `as_tibble()` before performing manipulations if the manipulation ends up dropping the .i or .t column. So perhaps if .i or .t will be dropped, return an error something like

```
This action will drop column(s) <column>. Coerce pibble into tibble with as_tibble() before performing this action. 
```
I think the above makes sense for how we deal with the dplyr methods. For functions in pmdplyr where .i or .t is likely to be dropped we should consider always returning tibbles.

**Comment by NickCH-K** [comment]
Yes, agreed, falling back to `tibble` is a better plan there.

All of the functions that drop `pibble` status are regular `dplyr` verbs in their `tbl_pb` form, so I think it makes sense to allow them without error but send a warning; otherwise, chaining commands could get pretty annoying. 

The real problem arises if those functions are called internally for calculation purposes, inside a `pmdplyr` function that will, in the end, return a `pibble`. I think the best plan is probably to coerce to `tibble` inside the function, and then convert back to `pibble` at the very end. This will probably speed the functions up too (by extremely small amounts).

**Comment by philip-khor** [comment]
> All of the functions that drop `pibble` status are regular `dplyr` verbs in their `tbl_pb` form, so I think it makes sense to allow them without error but send a warning; otherwise, chaining commands could get pretty annoying.

Hmm I think an extra `as_tibble()` in the chain shouldn't be too annoying ...  It's a trade-off between not knowing what you're getting and convenience. I don't think it's a good idea if the attributes of the dataframe are changing in the middle of the chain. If the attributes are changing, it should be explicit in code.

Unfortunately there's not much discussion of the type stability of tibble subclasses in https://principles.tidyverse.org/out-type-stability.html

Looks like `tsibble` has [similar behaviour](https://pkg.earo.me/tsibble/reference/tidyverse.html): 

> Column-wise verbs, including select(), transmute(), summarise(), mutate() & transmute(), keep the time context hanging around. That is, the index variable cannot be dropped for a tsibble. If any key variable is changed, it will validate whether it's a tsibble internally. Use as_tibble() to leave off the time context.

**Comment by NickCH-K** [comment]
Hmm, that does make sense. I think `panel_data` has similar behavior. This seems like a pretty straightforward fix for `select()`, `transmute()`, and `mutate()` (`mutate()` shouldn't need a fix at all since it can't drop variables), the bigger question there is whether the change in behavior will break any existing `pmdplyr` functions (although certainly it won't if I make everything a `tibble` in the internal workings). A harder one is how to get `rename()` and `summarize()` working.
