### ISSUE TITLE
`pdeclare()` doesn't have a consistent interface with other `tibble()` objects

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#3]
The `pdeclare()` function currently works by coercing a data frame to a pdeclare tibble. This is not consistent with the behaviour of `tibble::tibble()` and associated functions in tibble subclasses, which operate more like `list()`: 

```R
tibble(a, b = a * 2, c = 1)
```

Suggestions: 
1. Call the pmdplyr tibble object something else (e.g. pedal? pod? pebble?) and then point `as_pod()` to `pdeclare()` 
2. Change the behaviour of pmdplyr directly. This might affect existing analysis that uses pmdplyr

**Comment by NickCH-K** [comment]
Hmm, good point. I'll see what I can do about this.

**Comment by NickCH-K** [comment]
`pdeclare` has been retitled as `as_pdeclare` and usage throughout the package has been updated. New version of `pdeclare` creates a new `pdeclare` object consistent with `tibble` usage.
