### ISSUE TITLE
Consider adopting r-pkgs.org version number convention

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#31]
> A released version number consists of three numbers, `<major>.<minor>.<patch>` ... the first version of the package should be 0.0.0.9000. There are two reasons for this recommendation: first, it makes it easy to see if a package is released or in-development, and the use of the fourth place means that you’re not limited to what the next version will be. 0.0.1, 0.1.0 and 1.0.0 are all greater than 0.0.0.9000.

https://r-pkgs.org/description.html#version

**Comment by NickCH-K** [comment]
So does this imply that the version number would be 0.0.0.9000, or 0.2.1.9000? I do consider the package to be usable.

**Comment by philip-khor** [comment]
My understanding is that we should be going for 0.2.1.9000  just so when pmdplyr is reinstalled R will know it's a newer version 

I think what they're recommending is that CRAN versions would be e.g. 0.2.1 whereas versions installed via GitHub will be e.g. 0.2.1.9000

**Comment by NickCH-K** [comment]
Addressed in 487e31053c3924fbb18601d2e75082ff4ddb53e9
