### ISSUE TITLE
Preparation for CRAN

### ISSUE THREAD

**Issue by NickCH-K** [NickCH-K/pmdplyr#35]
As per 8604a72b02a360ba6154a6cbf71d940be8fbcc34, sending a 0.3.0 version to CRAN seems like a good call. It's clearly coming up on ready for it. I'm not sure when that's going to be feasible, as I'm not sure how much longer I'll be able to work as much on this as I have been. But in any case, here's the list of issues it would be very good to resolve before sending to CRAN:

- [x] Getting `bind_rows.tbl_pb` to work (it makes no sense that it doesn't work. I'm baffled as to why, when I write `bind_rows.tbl_pb` and then call `bind_rows(pibble, pibble)`, it calls the non-`tbl_pb` version of `bind_rows`).
- [x] Finish maximizing use of `dplyr` on all files (nearly done)
- [x] Turn everything to a `tibble` internally so we don't have to worry about dropping `pibble` status during calculations
- [x] Improve code coverage to, like, 80%+ in every file? Or at least covering everything important.
- [x] Speed up the `panel_locf` example - it's over 5s
- [x] Fix issue in dropchecker when `.i` and `.t` are blank

Added from your post:
* [x] Check that description is informative
* [x] Check licensing of included files
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [ ] Create RC branch (for bigger releases)
* [x] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()`
* [ ] Approve email

Wait for CRAN...

* [ ] Tag release
* [ ] Merge RC back to master branch
* [ ] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by philip-khor** [comment]
Would be good to add these issues to release milestones ([example](https://github.com/tidyverse/dplyr/milestone/15)). I think it's good to put the package out there on CRAN asap so that we can gather feedback. 

To keep things realistic, I would set point 1 (#27), point 2 (#21), and point 3 (#28) as 0.3.0 targets. I think the rest can be left for 0.4.0. Code coverage (#26) and methods (#5) are safe to leave out I think (tsibble has been on CRAN for a while and doesn't seem to implement as many methods as we have, and there's a lot of dplyr and tidyr functions out there that we'll lack methods for anyway. Plus I think we can improve coverage as we go.). 

I think point 4 (#36) seems like major enough work that it can be left for a future point release.

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by NickCH-K** [comment]
Sounds good. Finishing #3 will make #4 less pressing anyway. I do want to improve code coverage at least somewhat before release, if only because it shouldn't take super long, and the process of doing it turns up bugs to fix.

**Comment by NickCH-K** [comment]
Alright! The first chunk of checklist is done as of 78901b1e0037e794a3f327f498e06218249a6521.

In a few days I'm going to have a lot less time to work on this, and I'm not 100% familiar with all the items left on the checklist. Would it be possible for you to let me know which of those items I should be focusing on so that I can do them before I step back?

**Comment by NickCH-K** [comment]
In addition to the above checked off, I ran `devtools::check(args = "--as-cran") ` and the only problem was the note 

```
  Non-standard files/directories found at top level:
    '_pkgdown.yml' 'cran-comments.md' 'docs'
```

Not sure if we have to remove these before submission.

**Comment by NickCH-K** [comment]
`check_win_devel()` notes (probably all fine?)

```
Version contains large components (0.2.1.9012)

Possibly mis-spelled words in DESCRIPTION:
  pibble (11:193)
  tibble (11:174)

Found the following (possibly) invalid file URI:
  URI: .github/CODE_OF_CONDUCT.md```

**Comment by NickCH-K** [comment]
Oops - made a minor fix for `check_win_devel() ` but forgot to push it. So if you're running checks they might fail. I'll update once I get back to my laptop and can push the change.

**Comment by philip-khor** [comment]
> 
> 
> In addition to the above checked off, I ran `devtools::check(args = "--as-cran") ` and the only problem was the note
> 
> ```
>   Non-standard files/directories found at top level:
>     '_pkgdown.yml' 'cran-comments.md' 'docs'
> ```
> 
> Not sure if we have to remove these before submission.

Should be just adding these files to `.Rbuildignore`. 

>^cran-comments\.md$
>^_pkgdown\.yml$
>^docs$

**Comment by NickCH-K** [comment]
> 
> 
> Oops - made a minor fix for `check_win_devel() ` but forgot to push it. So if you're running checks they might fail. I'll update once I get back to my laptop and can push the change.

This is fixed now. I've also added those files to `.Rbuildignore`.

**Comment by philip-khor** [comment]
> 
> 
> Alright! The first chunk of checklist is done as of [78901b1](https://github.com/NickCH-K/pmdplyr/commit/78901b1e0037e794a3f327f498e06218249a6521).
> 
> In a few days I'm going to have a lot less time to work on this, and I'm not 100% familiar with all the items left on the checklist. Would it be possible for you to let me know which of those items I should be focusing on so that I can do them before I step back?

Not sure myself, this is new to me too... But just let me know which ones I can help out with. How about if I just work on 
- [x] rhub::check_for_cran()
- [ ] ~revdepcheck::revdep_check(num_workers = 4)~ - not needed, first submission will not have reverse deps 
- [x] rhub::check(platform = 'ubuntu-rchk')
- [x] rhub::check_with_sanitizers()
I think the last point is just to inform the maintainers if there are failures, which is unnecessary here.

**Comment by NickCH-K** [comment]
Sounds good, go for it. And you said that CRAN is closed now and opens later this month?

Nick Huntington-Klein
Assistant Professor of Economics
CSU Fullerton
(657) 278-3918, nickchk.com

________________________________

**Comment by philip-khor** [comment]
Yup, we're looking at August 19th at the earliest 

> The submission server team is on vacation from Aug 9, 2019 to Aug 18, 2019
https://cran.r-project.org/submit.html

**Comment by philip-khor** [comment]
I think I'm done with the checks. I'm getting similar notes, nothing to be concerned about I think. I'm running `rhub::check(platform = 'ubuntu-rchk')` but I suspect that's unnecessary. 

Version bump from dev to release can be done with `usethis::use_version()`. 

If we want to push further commits while waiting for CRAN to reopen, I'd suggest doing commits for the CRAN release on a RC branch. I think the remaining commit to do is to write a COPYRIGHTS file for the GPLv2-licensed SPrail - working on that atm.

**Comment by NickCH-K** [comment]
Do you think a RC branch is necessary? Also, what would be different about it (just a stable branch not to be updated, so it matches the CRAN version? Or dropping some GitHub-only files?)

**Comment by philip-khor** [comment]
Should be just a stable branch not to be updated except for updates requested by CRAN. 

I would say that RC branch is unnecessary, unless you want to continue on development while waiting for CRAN approval. I hear the CRAN review process might take a while.

**Comment by NickCH-K** [comment]
I'll probably skip it then. I'm planning to take a break until release.

**Comment by philip-khor** [comment]
Looks like the package may have been rejected? I'm happy to make the fixes for a resubmission.

**Comment by NickCH-K** [comment]
Oh yep we need something more in  `.Pkgignore` maybe

```
Thanks,

Found the following (possibly) invalid file URI:
URI: .github/CODE_OF_CONDUCT.md
From: README.md

If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: authors (year) <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.


Please fix and resubmit, and document what was (not) changed in the
submission comments.

Best,
Martina Schmirl
```

**Comment by philip-khor** [comment]
> Found the following (possibly) invalid file URI:
> URI: .github/CODE_OF_CONDUCT.md
> From: README.md

This one is a trivial fix - the code of conduct would not be in the build file since we ignore it in the buildignore file. Just replaced with the pkgdown code of conduct URL. 


> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available: authors (year) <https:...>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
> auto-linking.

I think we can ignore this? I can make a note in cran-comments.md that references are not relevant for the methods in this package.

**Comment by NickCH-K** [comment]
Same issue. I literally just had a baby this morning so this is all you

```
Thanks, we see:


Found the following (possibly) invalid file URI:
URI: .github/CODE_OF_CONDUCT.md
From: README.md

Please replace by a fuly specified URL.

Please fix and resubmit.

Best,
Uwe Ligges
```

**Comment by philip-khor** [comment]
That's great news, congrats! 

My bad, I forgot to knit README.Rmd after the fix. Just made PR and `devtools::submit_cran()`.

**Comment by NickCH-K** [comment]
This is what I got back. Very strange. Anything that might be causing this? Version stuff? Note the error does not occur on Debian, just Windows

```
* using log directory 'd:/RCompile/CRANincoming/R-devel/pmdplyr.Rcheck'
* using R Under development (unstable) (2019-08-19 r77043)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'pmdplyr/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'pmdplyr' version '0.3.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Nick Huntington-Klein <nhuntington-klein@fullerton.edu>'

New submission

Possibly mis-spelled words in DESCRIPTION:
  pibble (11:193)
  tibble (11:174)
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'pmdplyr' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... ERROR
Loading this package had a fatal error status code 1
Loading log:
Loading required package: dplyr
Error: package or namespace load failed for 'dplyr' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'tibble'
Error: package 'dplyr' could not be loaded
Execution halted
** DONE
Status: 1 ERROR, 1 NOTE```

**Comment by philip-khor** [comment]
I'm baffled too. I just ran the check on windows with R-hub on a dev version of R and [it works fine](https://builder.r-hub.io/status/pmdplyr_0.3.0.tar.gz-5b72d7d25eaa4e4f878b785d44b151ea). 

EDIT: Just posted [here](https://community.rstudio.com/t/error-submitting-package-to-cran/37849?u=philip_khor) on the RStudio Community. Honestly, I think it's an issue with CRAN but I can't be sure. 

IMO it doesn't sound like our issue, it sounds like an error that a re-run should resolve. I'm really not sure how to go about this. I'm thinking if we could contact the [CRAN team](mailto:cran-submissions@r-project.org) for additional feedback? 

> In case of problems related to the package, its check results or the partly automated check system, contact the CRAN team. 

EDIT: tested tibble on win-builder with dev, no issues.

**Comment by NickCH-K** [comment]
I'll contact them and see what's up.

**Comment by NickCH-K** [comment]
Hooray!

```
Yes, lokks like a false positive, I triggered new checks.
Best,
Uwe Ligges
```

**Comment by philip-khor** [comment]
Keeping an eye on progress here, it's currently being reviewed in newbies

https://cransays.itsalocke.com/articles/dashboard.html
