### ISSUE TITLE
Check licensing

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#38]
Relates to #35, since CRAN would want redistributed code to be properly licensed. 

`Scorecard` is [CC0-licensed](https://github.com/RTICWDT/college-scorecard/blob/dev/LICENSE.md) whereas `SPrail` is GPL2-licensed. While CC0 shouldn't be an issue, GPLv2 is a bit worrying: 

> 2. You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions:
>    a) You must cause the modified files to carry prominent notices stating that you changed the files and the date of any change.
>    b) You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.

It sounds to me like the modified `SPrail` would have to be GPL2-licensed to be on CRAN. Asking around if this will be an issue, but if we don't get feedback I think the license entry should be able to take two arguments.

**Comment by NickCH-K** [comment]
Oh dang, when I was putting the data together I made sure to check both were distributable, but didn't think about the potential issue of it being two separate licenses.
