### ISSUE TITLE
Bare column names across all arguments for `dplyr` verb variants, `as_pdeclare()`

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#6]
The `.filter` argument for `mutate_subset()` require logical vectors. This is not consistent with other `dplyr` functions as it interrupts piping workflows. 

Ideally, the arguments should support bare/unquoted variables, e.g. 

```R
SPrail %>%
 mutate_subset(promo_price = mean(price, na.rm = TRUE),
              .filter = fare == 'Promo',
              .i = c(origin, destination))
```
Implementation-wise, 

https://github.com/NickCH-K/pmdplyr/blob/83e2a40fd873f26f45287893a8d2abb1fffa01f7/R/major_mutate_variations.R#L170-L172
could be replaced with 

```R
  .df %>%
    dplyr::filter({{ .filter }}) %>%
    dplyr::summarize(...) -> summ
```
(requires `rlang` 0.4.0)

Similar comments for `as_pdeclare()`. For consistency with other packages, unquoted variables will be ideal. `tsibble::as_tsibble` takes bare column names:

```R
flights_tsbl <- flights %>%
  as_tsibble(
    key = c(carrier, flight), 
    index = sched_dep_datetime, 
    regular = FALSE
  )
```

The now retired `tibbletime` also uses [bare column names](https://business-science.github.io/tibbletime/reference/tbl_time.html).

**Comment by NickCH-K** [comment]
This is going to take a fair amount of overhaul for `.i` and `.t` but yeah it's something that needs to happen. This will also allow many of the places where the code uses base-R to manipulate data to be turned to `dplyr` verbs for consistency. I'll need to get reading up on quosures!

**Comment by NickCH-K** [comment]
This is in progress

**Comment by NickCH-K** [comment]
At long last! The package is updated to work with bare variable names now with daed341bc6f0abaa2db8a1556c41d1cb7e858954 . Granted, it does not take full advantage. It basically just converts them immediately into the string names we already had. But future commits can take more full advantage of `rlang`.
